name: Python_nambers

# Controls when the workflow will run
env:
  Python_file: simple.py

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch   
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  # This workflow contains a single job called "build"
  Python_nambers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env: 
      x: 40
      y: 55
    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell   
     # - name: Run a Python script
    #    run:   echo "deploy_target is ${{ inputs.Number_one }}"
        
      - name: Run a Python script 
        run: python3 ${{ env.Python_file }} ${{ env.x }} ${{ env.y }}
